---
- name: "Reload PostgreSQL meta unit service"
  ansible.builtin.systemd_service:
    name: postgresql
    state: reloaded

- name: "Reload PostgreSQL cluster service"
  ansible.builtin.systemd_service:
    name: postgresql@{{ postgresql_version }}-main
    state: reloaded
