---
- name: "Ensure GPG is installed, needed for APT key"
  ansible.builtin.apt:
    name: "gpg"

- name: "Add Caddy APT repository"
  ansible.builtin.deb822_repository:
    name: caddy
    types: deb
    uris: https://dl.cloudsmith.io/public/caddy/stable/deb/debian
    signed_by: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
    suites: "any-version"
    components:
      - "main"

- name: "Install Caddy"
  ansible.builtin.apt:
    name: "caddy"

- name: "Create caddy.env"
  when: setup_prometheus_node_exporter
  ansible.builtin.template:
    src: caddy.env.jinja2
    dest: /etc/caddy/caddy.env
    owner: root
    group: root
    mode: "0600"

- name: "Create systemd caddy override directory"
  when: setup_prometheus_node_exporter
  ansible.builtin.file:
    path: "/etc/systemd/system/caddy.service.d"
    state: directory
    owner: root
    group: root
    mode: '0644'

- name: "Create caddy override.conf"
  when: setup_prometheus_node_exporter
  ansible.builtin.template:
    src: override.conf.jinja2
    dest: "/etc/systemd/system/caddy.service.d/override.conf"
    owner: root
    group: root
    mode: "0600"

- name: "Create the Caddyfile"
  ansible.builtin.template:
    src: Caddyfile.jinja2
    dest: /etc/caddy/Caddyfile
    owner: root
    group: root
    mode: "0644"

- name: "Restart Caddy"
  ansible.builtin.systemd_service:
    name: caddy
    daemon_reload: true
    enabled: true
    state: restarted
